server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bolg?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  thymeleaf:
    cache: false

mybatis-plus:
  type-aliases-package: com.zxh.pojo
  #加载mybatis映射文件
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.zxh.dao: debug


